### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by varac** [SebDanielsson/docker-wireguard-transmission#3]
Please do proper releases so one could track them via the helpful `Watch releases` github feature.
Also you would have proper docker hub tags with it, instead of only `latest`. Thanks !

**Comment by SebDanielsson** [comment]
I've created a release now and added a tag to Docker Hub. Now :latest points to the latest release and the new :testing points to the master branch. I'm still pretty new to this stuff so please help if you see any errors. I'm thinking about the last two rows, are they formatted correctly? Is there a better way to enable tags for minor updates?

![Screenshot 2020-10-26 at 13 54 49](https://user-images.githubusercontent.com/20663065/97174797-dcae3300-1792-11eb-8b86-5b167342e10b.png)

**Comment by varac** [comment]
Hej @SebDanielsson thanks for doing this so fast. I don't have any experience with Automated Builds with Git-/Docker Hub (only with Gitlab), sorry. Someone else might help you better here.
Looking from an user perspective, it's good to have proper version tags that are the same for both for Github and Docker Hub.
I.e. if you tag and release `0.1` on Github, there should be a related `0.1` image on Docker Hub which is build from the same tag.
It doesn't matter if you upload it manually or automated (of course it gets handy to setup automated builds if you release often).

**Comment by varac** [comment]
As a docker user I'd like to pin a specific version (i.e. 0.1) and don't want to use `:lastest` or `:testing`, because they are moving targets and might change/break things, and I'd like to be in control of upgrading. That's why [semantic versioned](https://semver.org/) image tags are useful. :whale:
