### ISSUE TITLE
Issues Starting The Container/Webserver

### ISSUE THREAD

**Issue by naterz1204** [SebDanielsson/docker-wireguard-transmission#5]
Hi Seb! First off, thanks a bunch for putting in the work to get a simple, functioning wg-transmission container together for everyone. This may be a simple mistake in my configuration - in which case, I apologize for asking you to troubleshoot something I did wrong. I've got a decent docker setup running and am fairly used to configuring these. However, I'm having issues with getting the transmission webserver to respond once the container is started up. Attached is the container's log file which is relatively small so I didn't get much for ideas or solutions from it.. Also attached is the section for the container from my compose file. Any advice? 
[wgtranslog.txt](https://github.com/SebDanielsson/docker-wireguard-transmission/files/5453857/wgtranslog.txt)
[composesnippet.txt](https://github.com/SebDanielsson/docker-wireguard-transmission/files/5453866/composesnippet.txt)

**Comment by SebDanielsson** [comment]
I’m very sorry for being slow to respond. This fall-winter has been really busy for me... If you’re still experienceing issues just reply and I’ll try the container on a fresh install on Ununtu👍

**Comment by SebDanielsson** [comment]
Will cease development of this image since there is a more clean way of doing this.

Check out my other repo here:
https://github.com/SebDanielsson/compose-transmission-wireguard
