### ISSUE TITLE
Move away from --privileged

### ISSUE THREAD

**Issue by dza89** [SebDanielsson/docker-wireguard-transmission#7]
Definitely necessary:

  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" 

adapter is not coming up even with this settings however. Will update the issue later.

**Comment by SebDanielsson** [comment]
Did you find a solution? Every search I make I only see people saying that priviliged is required if you have AllowedIP=0.0.0.0/0 in the WireGuard config file.

**Comment by dza89** [comment]
Haven't got time yet to check it. In a few weeks.

**Comment by dza89** [comment]
I think this can be closed, since wireguard runs as a kernel module it's practically impossible as far as I see.

**Comment by dza89** [comment]
This can actually be done. But it has some constraints/limits.
We need to extract the kernel module, after that the container doesn't need to run privileged anymore. This is easy on kubernetes, but proves a bit of a challenge on a docker system.
https://math.rousse.me/sysadmin/2020/05/21/wireguard-k8s.html
